### PR TITLE
Switched to AsyncKeyedLock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
This library will improve performance and greatly reduce memory allocations through object pooling of SemaphoreSlim objects. On top it is passing on the cancellation token to the semaphore.

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@EricDahlvang ?

**Comment by MarkCiliaVincenti** [comment]
@EricDahlvang ?

**Comment by MarkCiliaVincenti** [comment]
@EricDahlvang ?

**Comment by MarkCiliaVincenti** [comment]
@EricDahlvang  are you interested or shall I close this PR?

**Comment by MarkCiliaVincenti** [comment]
@EricDahlvang  please let me know

**Comment by EricDahlvang** [comment]
Thanks @MarkCiliaVincenti Looks like a great library.

**Comment by MarkCiliaVincenti** [comment]
Thanks but now I noticed that the version is out of date, will create another PR.

**Pull request merged**
